"""
API v1 router
"""

from fastapi import APIRouter

# Create main API router
api_router = APIRouter()

# Basic health check endpoint
@api_router.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "ai-blog-assistant-api",
        "version": "1.0.0"
    }

# Content generation endpoint (mock)
@api_router.post("/content/generate")
async def generate_content():
    return {
        "title": "Sample Blog Post",
        "content": "This is a sample blog post generated by the AI Blog Assistant.",
        "status": "generated"
    }

# Templates endpoint (mock)
@api_router.get("/content/templates")
async def get_templates():
    return {
        "templates": [
            {"id": "blog_post", "name": "Blog Post", "description": "Standard blog post format"},
            {"id": "article", "name": "Article", "description": "Long-form article"},
            {"id": "social_media", "name": "Social Media", "description": "Short social media post"}
        ]
    }